spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8081/golfprogram
    username: root
    password:
  banner:
    location: banner.txt
  liquibase:
    change-log: sql/changelog.xml
    enabled: true
    url: jdbc:mysql://localhost:8081/golfprogram
    user: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  application:
    name: golf service

server:
  port: 8081
