spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:8081/golf_database
    username: root
    password: 123456
    #hikari:
  banner:
    location: banner.txt
  #liquibase:
   # change-log: classpath:sql/migrations/changelog.xml
   # enabled: true
   # url: jdbc:mysql://localhost:8081/golf_database
   # user: root
   # password: 123456
  #jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #hibernate:
     # ddl-auto: none
  #application:
    #name: golf service

#server:
  #port: 8081
