spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:8081/golf_database
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: golf
  main:
    banner-mode: off
  banner:
    location: banner.txt
  liquibase:
    change-log: classpath:sql/migrations/changelog.xml
    enabled: true
    url: ${spring.datasource.jdbc-url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  application:
    name: golf service

server:
  port: 8081
