spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/golfprogram
    username: root
    password: 123456
  banner:
    location: banner.txt
  liquibase:
    change-log: classpath:sql/migrations/changelog.xml
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  application:
    name: golf service

